# Generated by Django 5.2.3 on 2026-02-24 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_roblox_user_id', models.BigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('voting', 'voting'), ('done', 'done'), ('skipped', 'skipped')], default='pending', max_length=20)),
                ('final_value', models.CharField(blank=True, max_length=255, null=True)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('playing', 'playing'), ('finished', 'finished')], default='waiting', max_length=20)),
                ('owner_roblox_user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_sessions', to='poker.item')),
            ],
            options={
                'db_table': 'sessions',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='poker.session'),
        ),
        migrations.CreateModel(
            name='SessionMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roblox_user_id', models.BigIntegerField()),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('owner', 'owner'), ('player', 'player')], default='player', max_length=20)),
                ('status', models.CharField(choices=[('active', 'active'), ('left', 'left'), ('kicked', 'kicked')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='poker.session')),
            ],
            options={
                'db_table': 'session_members',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roblox_user_id', models.BigIntegerField()),
                ('value', models.CharField(max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.item')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='poker.session')),
            ],
            options={
                'db_table': 'votes',
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['status'], name='sessions_status_2c94db_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['owner_roblox_user_id'], name='sessions_owner_r_ced92f_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['updated_at'], name='sessions_updated_fe65fc_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['session'], name='items_session_796567_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['session', 'position'], name='items_session_b649af_idx'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['session', 'status'], name='items_session_414d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmember',
            index=models.Index(fields=['session'], name='session_mem_session_87b343_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmember',
            index=models.Index(fields=['roblox_user_id'], name='session_mem_roblox__a621b7_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionmember',
            index=models.Index(fields=['status'], name='session_mem_status_95024d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionmember',
            unique_together={('session', 'roblox_user_id')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['session'], name='votes_session_78ff46_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['item'], name='votes_item_id_b6d47c_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['roblox_user_id'], name='votes_roblox__28a1e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('item', 'roblox_user_id')},
        ),
    ]
