# Generated by Django 6.0.2 on 2026-03-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vote',
            name='votes_session_78ff46_idx',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='session',
        ),
    ]
