# Generated by Django 5.2.3 on 2026-03-06 17:48

import django.db.models.deletion
from django.db import migrations, models


def deduplicate_session_members(apps, schema_editor):
    SessionMember = apps.get_model("poker", "SessionMember")

    grouped = {}
    for member in SessionMember.objects.all().order_by("roblox_user_id", "-updated_at", "-id"):
        grouped.setdefault(member.roblox_user_id, []).append(member.id)

    ids_to_delete = []
    for _, member_ids in grouped.items():
        # Keep the most recent member row for each Roblox user id.
        ids_to_delete.extend(member_ids[1:])

    if ids_to_delete:
        SessionMember.objects.filter(id__in=ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessionmember',
            unique_together=set(),
        ),
        migrations.RunPython(deduplicate_session_members, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='sessionmember',
            name='roblox_user_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='sessionmember',
            name='role',
            field=models.CharField(choices=[('owner', 'owner'), ('player', 'player'), ('guest', 'guest')], default='player', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionmember',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='poker.session'),
        ),
        migrations.AlterField(
            model_name='sessionmember',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=20),
        ),
        migrations.RemoveField(
            model_name='sessionmember',
            name='last_seen_at',
        ),
    ]
