# Generated by Django 6.0.2 on 2026-03-27 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_alter_sessionmember_unique_together_and_more'),
        ('poker', '0002_remove_vote_votes_session_78ff46_idx_and_more'),
    ]

    operations = [
    ]
