# Generated by Django 6.0.2 on 2026-03-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_merge_20260327_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='owner_server_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
