# Generated by Django 6.0.2 on 2026-03-27 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_session_owner_server_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='owner_server_id',
            field=models.BigIntegerField(),
        ),
    ]
